import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.swifttranslator.com/');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('matavaedakarannathiyenavaa');
  await page.locator('div').filter({ hasText: /^මටවැඩකරන්නතියෙනවා$/ }).click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama @@office## yanavaa!!');
  await page.getByText('මම @@office## යනවා!!').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('assignment eka 25-01-2026 wenakan submit karanna');
  await page.getByText('assignment එක 25-01-2026 w').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama office meeting eka cancel kalaa today');
  await page.getByText('මම office meeting එක cancel').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mAma OFfiCe YanAVaa AdHa');
  await page.getByText('මම ඔෆ්ෆිCඑ YඅනVආ අඩ්හ').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama gedhara yanavaa????!!!');
  await page.getByText('මම ගෙදර යනවා????!!!').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama iilagasathiyehamBAvemu');
  await page.getByText('මම ඊලගසතියෙහම්ඹවෙමු').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('matahetaofficeyannathiyenavaasahahetaassignmentekakthiyenavaa');
  await page.locator('div').filter({ hasText: /^මටහෙටඔෆ්ෆිcඑයන්නතියෙනවාසහහෙටාස්සිග්න්මෙන්ටෙකක්තියෙනවා$/ }).click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama adha campus yanavaa 😊');
  await page.getByText('මම අද campus යනවා 😊').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama vathura kooppa dhekak bivvaa');
  await page.getByText('මම වතුර කෝප්ප දෙකක් බිව්වා').click();
  await page.getByLabel('Clear').click();
});